spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  customer-service:
    url: ${CUSTOMER_SERVICE_URL}
  tenant-service:
    url: ${TENANT_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  company-service:
    url: ${COMPANY_SERVICE_URL}
  booking-service:
    url: ${BOOKING_SERVICE_URL}

logging:
  level:
    root: WARN
    com.svrmslk.gateway: INFO
    org.springframework.cloud.gateway: INFO