# src/main/resources/application-prod.yml
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-service-prod-group}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

kafka:
  topics:
    email-notification-requested: prod.email-notification-requested
    inapp-notification-requested: prod.inapp-notification-requested

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}
  from-name: ${SENDGRID_FROM_NAME}
  timeout-seconds: 10

resilience:
  ratelimit:
    max-requests-per-window: 100
    window-duration-seconds: 60

logging:
  level:
    root: WARN
    com.svrmslk.notificationservice: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

server:
  port: ${SERVER_PORT:8080}